<?php

namespace Prunatic\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
    private function qbCityBySlugWithProvinceAndCountry()
    {
        $qb = $this->createQueryBuilder('c');
        $qb
            ->select('c')
            ->innerJoin('c.province', 'p')
            ->innerJoin('p.country', 'co')
            ->where($qb->expr()->eq('c.slug', ':city'))
            ->andWhere($qb->expr()->eq('p.slug', ':province'))
            ->andWhere($qb->expr()->eq('co.slug', ':country'))
        ;

        return $qb;
    }

    public function findBySlugWithProvinceAndCountry($city, $province, $country)
    {
        $qb = $this->qbCityBySlugWithProvinceAndCountry();

        return $qb
            ->setParameters(array(
                'city' => $city,
                'province' => $province,
                'country' => $country,
            ))
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
