imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: true
    bundles:        [MopaBootstrapBundle, PrunaticWebBundle]
    #java: /usr/bin/java
    filters:
        less:
            node: %node_bin%
            node_paths: [%node_paths%]
            apply_to: "\.less$"
        cssrewrite: ~
        cssembed:
            jar: %kernel.root_dir%/Resources/java/cssembed-0.4.5.jar
            apply_to: "\.css$"
            #apply_to: "\.css$|\.less$" # embedding less is not working
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
            apply_to: "\.css$"
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
            #apply_to: "\.js$"
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
        types:
            point: Prunatic\WebBundle\Doctrine\Type\PointType
        mapping_types:
            enum: string
            point: point

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

stof_doctrine_extensions:
    default_locale: ca
    # Only used if you activated the Uploadable extension
    uploadable:
        validate_writable_directory: true
        # Default file path: This is one of the three ways you can configure the path for the Uploadable extension
        default_file_path:  /uploads/ #     %kernel.root_dir%/../web/uploads

    orm:
        default:
            timestampable: true
            uploadable: true
            sluggable: true