prunatic_web_homepage:
    pattern:  /
    defaults: { _controller: PrunaticWebBundle:Default:index }
    methods: GET

prunatic_web_legal:
    pattern:  /avis-legal.html
    defaults: { _controller: PrunaticWebBundle:Default:legal }
    methods: GET

prunatic_web_faq:
    pattern:  /preguntes-frequents.html
    defaults: { _controller: PrunaticWebBundle:Default:faq }
    methods: GET

prunatic_shout_create:
    pattern:  /el-megafon.html
    defaults: { _controller: PrunaticWebBundle:Shout:create }

prunatic_shout_show:
    pattern:  /crit-{id}.html
    defaults: { _controller: PrunaticWebBundle:Shout:show }
    methods: GET
    requirements:
        id:  \d+

prunatic_shout_report:
    pattern:  /reportar-crit-inapropiat.html
    defaults: { _controller: PrunaticWebBundle:Shout:report }
    methods: POST

prunatic_shout_vote:
    pattern:  /votar-per-un-crit.html
    defaults: { _controller: PrunaticWebBundle:Shout:vote }
    methods: POST

prunatic_shout_remove:
    pattern:  /silenciar-un-crit.html
    defaults: { _controller: PrunaticWebBundle:Shout:requestRemoval }
    methods: POST

prunatic_shout_confirm_remove:
    pattern:  /confirmar-silenciar-un-crit.html?token={token}
    defaults: { _controller: PrunaticWebBundle:Shout:confirmRemoval }
    methods: GET

prunatic_shout_newest:
    pattern:  /ultims-crits-afegits.html
    defaults: { _controller: PrunaticWebBundle:Shout:newest }
    methods: GET

prunatic_shout_top_rated:
    pattern:  /crits-mes-valorats.html
    defaults: { _controller: PrunaticWebBundle:Shout:topRated }
    methods: GET

prunatic_shout_show_map:
    pattern:  /mapa-del-crit-{id}.html
    defaults: { _controller: PrunaticWebBundle:Shout:showMap }
    methods: GET

prunatic_shout_nearby:
    pattern:  /crits-mes-propers-al-crit-{id}.html
    defaults: { _controller: PrunaticWebBundle:Shout:nearbyShouts }
    methods: GET
    requirements:
        id:  \d+