prunatic_web_homepage:
    pattern:  /
    defaults: { _controller: PrunaticWebBundle:Default:index }

prunatic_web_legal:
    pattern:  /avis-legal.html
    defaults: { _controller: PrunaticWebBundle:Default:legal }

prunatic_web_faq:
    pattern:  /preguntes-frequents.html
    defaults: { _controller: PrunaticWebBundle:Default:faq }

prunatic_shout_create:
    pattern:  /afegir-un-crit.html
    defaults: { _controller: PrunaticWebBundle:Shout:create }

prunatic_shout_show:
    pattern:  /crit-{id}.html
    defaults: { _controller: PrunaticWebBundle:Shout:show }
    requirements:
        id:  \d+

prunatic_shout_report:
    pattern:  /reportar-crit-inapropiat.html
    defaults: { _controller: PrunaticWebBundle:Shout:report }
    methods: POST

prunatic_shout_vote:
    pattern:  /votar-per-un-crit.html
    defaults: { _controller: PrunaticWebBundle:Shout:vote }
    methods: POST
