parameters:
    prunatic_web.notification_manager.class: Prunatic\WebBundle\Service\NotificationManager

services:
    prunatic_web.notification_manager:
        class: %prunatic_web.notification_manager.class%
        arguments: [@mailer, @templating]
