parameters:
#    prunatic_web.example.class: Prunatic\WebBundle\Example

services:
#    prunatic_web.example:
#        class: %prunatic_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
